// projectsData.jsx - Centralized project data (UPDATED with new templates)

export const templatesProjects = [
   {
    id: 13,
    title: "Bebold1",
    image: "https://imgur.com/HVK8YJC.png",
    website: "https://bebold1.netlify.app/",
  },
    {
    id: 5,
    title: "Vessaaaa",
    image: "https://imgur.com/Vk5cVxx.png",
    website: "https://vessaaaa.netlify.app/",
  },
   {
    id: 10,
    title: "Sonnex",
    image: "https://imgur.com/3XpFeo9.png",
    website: "https://sonnex.netlify.app/",
  },
   {
    id: 15,
    title: "FCUK",
    image: "https://imgur.com/Q1ifGcu.png",
    website: "https://fcuk-ss-template.netlify.app/",
  },
  {
    id: 16,
    title: "Metaforge",
    image: "https://imgur.com/AaC0mKP.png",
    website: "https://poetic-profiterole-df0c6c.netlify.app/",
  },
    {
    id: 22,
    title: "Intro",
    image: "https://imgur.com/j2zXUgt.png",
    website: "https://visionsingle.netlify.app/",
  },
  {
    id: 23,
    title: "Prism",
    image: "https://imgur.com/1eGRs3d.png",
    website: "https://prism-ss-template.netlify.app/",
  },
  {
    id: 24,
    title: "Gaming",
    image: "https://imgur.com/MwlvTk8.png",
    website: "https://gaming-ss-template.netlify.app/",
  },
    {
    id: 19,
    title: "Imageon",
    image: "https://imgur.com/sjcWnW9.png",
    website: "https://imageon-ss-template.netlify.app/",
  },
  {
    id: 20,
    title: "Robotics Revolution",
    image: "https://imgur.com/cO59Wft.png",
    website: "https://robotech-ss-temmplate.netlify.app/",
  },
   {
    id: 21,
    title: "Studi0",
    image: "https://imgur.com/PGEustu.png",
    website: "https://studio-ss-template.netlify.app/",
  },
    {
    id: 26,
    title: "Bento",
    image: "https://imgur.com/SvNuOwk.png",
    website: "https://3d-bentooo.netlify.app/",
  },
  {
    id: 27,
    title: "Services",
    image: "https://imgur.com/YS4WuWN.png",
    website: "https://sstemplate1.netlify.app/",
  },
   {
    id: 30,
    title: "Portfolio",
    image: "https://imgur.com/QoQ3NKd.png",
    website: "https://intro-ss-template.netlify.app/",
  },
  {
    id: 31,
    title: "3DScroll Website",
    image: "https://imgur.com/naqtBO2.png",
    website: "https://space-ss-template.netlify.app/",
  },
  
  {
    id: 33,
    title: "Luminar Craft",
    image: "https://imgur.com/0ntiKu3.png",
    website: "https://luminarcraft-ss-template.netlify.app/",
  },
  {
    id: 34,
    title: "Services",
    image: "https://imgur.com/bsn3PuO.png",
    website: "https://services-ss-template.netlify.app/",
  },
  {
    id: 35,
    title: "Time Travel",
    image: "https://imgur.com/MfnoXfX.png",
    website: "https://timetravel1.netlify.app/",
  },
  {
    id: 36,
    title: "Client Portfolio",
    image: "https://imgur.com/4pADS3u.png",
    website: "https://sahithimorampudiportfolio.netlify.app/",
  },
  {
    id: 37,
    title: "TECH EVOLUTION",
    image: "https://imgur.com/WzGqSiJ.png",
    website: "https://1950-2050.netlify.app",
  },
  {
    id: 38,
    title: "Portfolio",
    image: "https://imgur.com/7AYNo9b.png",
    website: "https://portfolio-ss-template.netlify.app/",
  },
  {
    id: 39,
    title: "White Template",
    image: "https://imgur.com/BlCuRDf.png",
    website: "https://white-ss-template.netlify.app/",
  },
  {
    id: 40,
    title: "Veue",
    image: "https://imgur.com/2I7EQXU.png",
    website: "https://veue-ss-template.netlify.app/",
  },
  {
    id: 41,
    title: "Red Theme",
    image: "https://imgur.com/NM1Gl3x.png",
    website: "https://redtheme-ss-template.netlify.app/",
  },
  {
    id: 42,
    title: "Client Portfolio",
    image: "https://imgur.com/qewg0mX.png",
    website: "https://muteesportfolio.netlify.app/",
  },
  {
    id: 43,
    title: "CYBER JUNGLE",
    image: "https://imgur.com/8l7CBm4.png",
    website: "https://cyberjunglessk.netlify.app",
  },
  {
    id: 44,
    title: "1950-2050",
    image: "https://imgur.com/KvBzTel.png",
    website: "https://1950-2050.netlify.app/",
  },
  {
    id: 45,
    title: "WILDLIFE",
    image: "https://imgur.com/etjs1HV.png",
    website: "https://wildlifessk.netlify.app",
  },
  {
    id: 46,
    title: "PRO HEALTH",
    image: "https://imgur.com/B2v6MJH.png",
    website: "https://prohealthssk.netlify.app",
  },
  {
    id: 47,
    title: "MELODY PULSE",
    image: "https://imgur.com/3mV3g4v.png",
    website: "https://melodypulsessk.netlify.app",
  },
  {
    id: 48,
    title: "KINGDOM RUSH",
    image: "https://imgur.com/faTJCBo.png",
    website: "https://kingdom-rush.netlify.app/",
  },
  {
    id: 49,
    title: "RESUME BUILDER",
    image: "https://imgur.com/Swlckqm.png",
    website: "https://resumebuilderssk.netlify.app",
  },
  {
    id: 50,
    title: "SOLAR",
    image: "https://imgur.com/YFyxZ0o.png",
    website: "https://solarssk.netlify.app",
  },
  {
    id: 51,
    title: "RESTAURANT",
    image: "https://imgur.com/stjW8BW.png",
    website: "https://restaurantssk.netlify.app",
  },
  {
    id: 52,
    title: "TRAVEL PLANNER",
    image: "https://imgur.com/s9Ddwc0.png",
    website: "https://travelplannerssk.netlify.app",
  },
  {
    id: 53,
    title: "GAME STORE",
    image: "https://imgur.com/w33xXou.png",
    website: "https://gamestoressk.netlify.app",
  },
  {
    id: 1,
    title: "Reasonate",
    image: "https://imgur.com/iNXe7A0.png",
    website: "https://reasonate.netlify.app/",
  },
 
  {
    id: 4,
    title: "Coffeee11",
    image: "https://imgur.com/8xk6zv5.png",
    website: "https://coffeee11.netlify.app/",
  },
  {
    id: 6,
    title: "Defective",
    image: "https://imgur.com/uegOnBp.png",
    website: "https://defective.netlify.app/",
  },
  {
    id: 7,
    title: "Ekvator",
    image: "https://imgur.com/ykIXEjH.png",
    website: "https://ekvator.netlify.app/",
  },
  {
    id: 8,
    title: "Introspace",
    image: "https://imgur.com/V6h7oNZ.png",
    website: "https://introspace.netlify.app/",
  },
  {
    id: 9,
    title: "Rydex",
    image: "https://imgur.com/yalMOA8.png",
    website: "https://rydex.netlify.app/",
  },
  {
    id: 11,
    title: "Tutomile",
    image: "https://imgur.com/882sTJc.png",
    website: "https://tutomile.netlify.app/",
  },
  {
    id: 12,
    title: "Willey11",
    image: "https://imgur.com/jV2JbKz.png",
    website: "https://willey11.netlify.app/",
  },
  {
    id: 14,
    title: "Arqline1",
    image: "https://imgur.com/AFTlaql.png",
    website: "https://arqline1.netlify.app/",
  },
  {
    id: 18,
    title: "Craftplay",
    image: "https://imgur.com/ECB6Vak.png",
    website: "https://craftplay-ss-template.netlify.app/",
  },
  {
    id: 25,
    title: "Bitjoy",
    image: "https://imgur.com/OWhjtKZ.png",
    website: "https://food-bite.netlify.app/",
  },
  {
    id: 28,
    title: "Services",
    image: "https://imgur.com/wMW6tqs.png",
    website: "https://sswebservicess.netlify.app/",
  },
 
];